
tasks:
  - init: npm install && npm run build
    command: |
      echo "Setting Environment Variable for gitpod users..."
      export HMR_HOST=`gp url 3000`
      echo "Starting Dev Server..."
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode
    
    - fivethree.vscode-svelte-snippets

    - bradlc.vscode-tailwindcss

    - heybourn.headwind

github:
  prebuilds:
    master: true
    branches: true
    pull: true